Python-roborock/python-roborock

roborock/api.py
roborock/containers.py
roborock/roborock_queue.py

I am trying to get the custom component into a state that would be approved by Home Assistant as a core integration. Part of that process includes adding typing inside the component, it becomes a bit easier if the underlying api has typing as well. there were some parts I wasn't sure about such as the queue items, and what all data types can be returned from the api, so they are just "Any" for  now.
As far as preparing the integration to get it to a good enough state for Home Assistant, I'd love to talk to you about that if you're interested. I've gotten a decent bit of work done. and with your help, we could definitely get it up for review in a week or two.

Added some typing throughout api

---

roborock/roborock_queue.py

Accidentally introduced this when I was adding typing

Remove circular dependenacy

---

pyproject.toml
roborock/roborock_queue.py

wait_for creates a task, async_timeout does the same work and avoids the task creation
This is one of the current optimizations they are making on HA core.
Sorry to be making so many PRS!

Change to timeout from wait_for

---

pyproject.toml

version 3.16 causes a version discrepancy as version 3.17 is required by another integration in HA core.

Bump pycryptodome to 3.17

---

roborock/__init__.py
roborock/code_mappings.py
roborock/containers.py

Getting an integration approved in HA is complicated. The larger the PR, the less likely it will be to be reviewed at any time soon. 
So I moved the code mappings to the api to decrease the file size of vacuum.py.
We don't have to do this if you are against this. 
This is a breaking change for the hacs integration. unless I make the same changes over there.
Let me know your thoughts.

Moved code mappings to api

---

.github/workflows/ci.yml
pyproject.toml
setup.py

So - this is something I've done for a few other pypi projects, but I've never done it in the middle of the project like this. So it may take some testing/ tuning.
You'll have to get an access token for pypi https://test.pypi.org/help/#apitoken
and a github token. And allow actions permissions to write on the repository.
This will when you merge into main, automatically create a changelog, bump the version, put out a release on github, and then put out a pypi release.
We need a changelog for HA core.
It means we should tag our commits with chore: (something small, doesn't need a version bump)
fix: Fixes an existing bump, needs a small version bump
feat: A new feature
If you don't want to do this, that is fine, but we do need to create a changelog at some point for HA if nothing else.
I'd …

feat: Add automatic release

---

roborock/api.py
roborock/code_mappings.py
tests/test_api.py

Added test and fix bugs with the docking commands.

fix: bug with dock commands

---

README.md
pyproject.toml

Added more information for the pypi repository and added readme

chore: pypi cleanup

---

roborock/code_mappings.py

I think this is what you meant. Seems to fix issues as well.
I attempted to create RoborockCode a subclass of RoborockEnum, but it gave errors being unpacked in the import, so I went this approach as well.
per #25

fix: make roborockCode through function

---

roborock/typing.py

I connected to my phone through wireshark, and the prefix for custom mode was x00w not x00\x87.
I was timing out and the command would end up sending after 10 seconds, but with this fix, it is instant.
If you merge this and #27 in, I think I have fixed all of the bugs for the core version (outside of the dict issues, but I'm not sure if there are any direct bugs from that.

fix: changed prefix for set_custom_mode

---

roborock/typing.py

We already assume that it can be none whenever we update it, but we don't type it to correspond to that fact.

fix: assume device prop attr can be none

---

roborock/typing.py

I accidentally only debuged segment clean, I'll try to do zoned clean later.

fix: changed prefixes for debugged commands

---

roborock/api.py

related to https://github.com/humbertogontijo/homeassistant-roborock/issues/245
I added this when I was fixing things with mypy - but it seems like it isn't actually being passed as the enum, and it isn't worth taking the time to fully debug as the check was mainly just a dev check and not a user check.

fix: removed enum type check

---

roborock/api.py
roborock/cli.py
roborock/cloud_api.py
roborock/code_mappings.py
roborock/local_api.py
tests/conftest.py
tests/test_api.py
tests/test_containers.py

Added a check if it is missing, return "UNKNOWN" which is now on all enums, but does not show up in lists.
Thoughts?

fix: add functionality for missing enum values

---

roborock/containers.py
tests/test_util.py

Seems like the consensus in the other thread was that time is the way to go for now. Neither fully encompass it, but time seems to be the best case.
So as long as it is good with you, I'm adding datetime time back to our timer objects

fix: add datetime_time back to timers

---

roborock/api.py
roborock/local_api.py
roborock/roborock_typing.py

Ok figured it out, the issue is with 24.0 of python-roborock.
Something with the valley timer and dnd timer being in the get_props.
Which in my opinion, we shouldn't be doing. If you look at how I do it in core, for entities outside of status, I have non-coordinated entities, these entities make the api call directly, that way if they aren't supported or if the user disables that entity, that call wont get made. Or If I update that entity, i.e. a switch on, I can just request the new status of that entity, rather than doing an entire coordinator refresh.
The issue stems with the valley timer, not sure why but that is causing all of the issues.
But for now I'm removing these from props as long as that is fine with you. And if I have time, I will try to rework the switches on …

fix: remove dnd timer and valley electricity from props

---

roborock/api.py
roborock/command_cache.py
roborock/roborock_message.py
tests/test_api.py

The mqtt client have messages for some attribute changes that are instantly. I'm creating some use for it here

feat: adding status and consumable listeners

---

pyproject.toml

Currently, there is a lock for construct in HA core based off of some other integrations, I'm working on removing it, but for now for test to pass I need to go back to the older version of construct
It may take some time as I need to get my PRs approved for other peoples integrations

fix: downgrade construct

---

roborock/cloud_api.py

The mqtt client now logs exceptions like `Error doing job: Task exception was never retrieved [...] RoborockTimeout: id=0 Timeout after 4 seconds` when it's already connected.
This PR fixes that by only calling `_async_response` when we actually need to connect. (Including the same-ish fix for disconnect.)
Full log entry:
```
2023-08-05 13:32:15.078 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved:   File "/home/vscode/.local/bin/hass", line 8, in <module>
sys.exit(main())
File "/home/vscode/.local/lib/python3.11/site-packages/homeassistant/__main__.py", line 214, in main
exit_code = runner.run(runtime_conf)
File "/home/vscode/.local/lib/python3.11/site-packages/homeassistant/runner.py", line 179, in run
return …
```

fix: resolve unawaited task errors on connect/disconnect

---

tests/test_api.py

Fixes test warning after #103 (`coroutine 'RoborockClient._wait_response' was never awaited`)

test: fix sync_connect test

---

pyproject.toml
roborock/api.py
roborock/cli.py
roborock/cloud_api.py
roborock/code_mappings.py
roborock/command_cache.py
roborock/containers.py
roborock/local_api.py
roborock/protocol.py
roborock/roborock_message.py
roborock/roborock_typing.py
roborock/util.py

pyupgrade changes all of our optionals to be | None and a few other changes

chore: add pyupgrade to ruff

---

roborock/api.py
roborock/cloud_api.py
roborock/containers.py
roborock/local_api.py

Instead of getting status each time we need it, we get it once so it is always available.
As well, we Shouldn't set the cache based off of listener if nothing exist, this was causing a few issues when I was testing robustness of being able to set up in core when the device is offline and then comes online

fix: status reworking

---

roborock/code_mappings.py

Add Mop Code 207 to eliminate error:
```
Logger: roborock.code_mappings
Source: runner.py:186
First occurred: 5:41:40 PM (1 occurrences)
Last logged: 5:41:40 PM
Missing RoborockMopIntensityS5Max code: 207 - defaulting to 200
```

fix: Add S5Max Mop Code 207

---

roborock/api.py

mypy yells about not having a py.typed file that mars our repository as a typed repository. 
Also sometimes padding fails, and I don't know why, so I am adding a exception to better help diagnose.

fix: error catch and typing

---

roborock/const.py

Related PR: https://github.com/humbertogontijo/homeassistant-roborock/pull/536
https://home.miot-spec.com/spec/roborock.vacuum.a30
<details>
<summary>Miiot details</summary>
```json
{
"did": <redacted>,
"uid": <redacted>,
"token": <redacted>,
"name": "Roborock G10",
"pid": 0,
"localip": <redacted>,
"mac": <redacted>,
"ssid": <redacted>,
"bssid": <redacted>,
"rssi": -37,
"longitude": "0.00000000",
"latitude": "0.00000000",
"show_mode": 1,
"model": "roborock.vacuum.a30",
"permitLevel": 16,
"isOnline": false,
"spec_type": "urn:miot-spec-v2:device:vacuum:0000A006:roborock-a30:1",
"extra": {
"isSetPincode": 0,
"pincodeType": 0,
"fw_version": "4.3.5_1292",
"isSubGroup": false,
"showGroupMember": false,
"split": {}
},
"orderTime": 1672797489,
"freqFlag": true,
"hide_mode": 0,
"last_online": …
```

Added: Roborock G10 Variant- roborock.vacuum.a30

---

roborock/api.py
roborock/code_mappings.py
roborock/const.py
roborock/containers.py
roborock/roborock_message.py

The product api had some good information including new status codes, some status codes for the dyad series, model numbers, etc.

fix: add information from product api

---

docs/source/usage.rst

Noted a couple of (minor) typos in the documentation referring to what is presumably old commands: `--username` instead of `--email` and `list_devices` instead of `list-devices`.

Fix reference to deprecated command

---

roborock/code_mappings.py

Solves the warning 
```Missing RoborockMopIntensityS8MaxVUltra code: 203 - defaulting to 200```
if command "get_status" is sent with return_type=S8MaxvUltraStatus

fix: add missing value "high = 203" to RoborockMopIntensityS8MaxVUltra

---

roborock/version_1_apis/roborock_client_v1.py

Oddly enough - sometimes two records can apparently come back for one timestamp - while that makes no logical sense, this handles it.

fix: handle weird clean record response

---

docs/source/api_commands.rst

This change adds documentation for the API function `reset_consumable`.
It adds information about the format of parameters for the function.

chore: Update documentation for reset_consumable

---

roborock/code_mappings.py

Newest roborock s8 maxv has one more mop intensity setting. I am open to changing its name

fix: S8 maxv highest mop intensity setting

---

roborock/version_1_apis/roborock_client_v1.py

I was checking what else is missing for s8 maxv. This model has a dock that washes the mop and also fills the robot. So I think it should be included in this list.
Please let me know if I have to do anything else.

fix: s8 maxv has a wash and fill dock

---

roborock/code_mappings.py

With current release (i.e adding the dock from https://github.com/humbertogontijo/python-roborock/pull/213) following warn messages appear within home assistant:
```
2024-06-06 10:06:10.775 WARNING (MainThread) [roborock.code_mappings] Missing RoborockDockWashTowelModeCode code: 10 - defaulting to 'unknown'
2024-06-06 10:06:19.505 WARNING (Thread-2 (_thread_main)) [roborock.code_mappings] Missing RoborockFanSpeedS8MaxVUltra code: 101 - defaulting to 105
2024-06-06 10:06:30.545 WARNING (Thread-2 (_thread_main)) [roborock.code_mappings] Missing RoborockFanSpeedS8MaxVUltra code: 103 - defaulting to 105
2024-06-06 10:06:31.922 WARNING (Thread-2 (_thread_main)) [roborock.code_mappings] Missing RoborockFanSpeedS8MaxVUltra code: 104 - defaulting to 105
2024-06-06 10:08:30.442 WARNING (Thread-2 …
```

S8MaxVUltra is missing some code mappings

---

roborock/code_mappings.py
roborock/version_1_apis/roborock_client_v1.py

I have a Q Revo Pro / P10 Pro which triggers the following warning:
`Missing RoborockDockTypeCode code: 9 - defaulting to 'unknown'`

feat: add q revo pro/p10 pro support

---

roborock/containers.py
tests/test_containers.py

Finally did this to end my dacite dependency suffering

feat: remove dacite

---

roborock/api.py
roborock/roborock_message.py
roborock/util.py
roborock/version_1_apis/roborock_client_v1.py

chore: Add some async improvements

---

.github/workflows/ci.yml

I have no idea if this will work tbh.
But we are so behind on the semantic release versioning it isn't working with the newer python versioning required for the map parser.
I took this config directly from their migration guide.

fix: bump semantic release

---

.github/workflows/ci.yml

Ci is still using the wrong version of python. I'm trying to explicitly set it here.

fix: set python version in ci

---

.github/workflows/ci.yml

I think i may finally have it figured out.
So long as the GH_TOKEN has full permission, this should work.

fix: hopefully finalize semantic release

---

.github/workflows/ci.yml

This works on the release branch. If I have the valid permissions, it should work here as well.
You could potentially add : "semantic-release" to overrides for branch protections. I do seem to have more permissions, but I can't see the settings page to do it myself. Hopefully it should work with my github_token

fix: repair semantic release

---

.github/workflows/ci.yml
roborock/containers.py

This fixes a broken change from api issues.
I also switched it back to GH_TOKEN, I don't have a real fix yet, but could you please merge it in, since you have permissions it should work.

fix: container issue from api change and ci update

---

roborock/code_mappings.py
roborock/containers.py

The QRevo Master mop mode was missing and was preventing successful initialization of the Roborock Home Assistant component.

fix: add support for QRevo Master mop mode

---

roborock/api.py

Update log message about invalid state to also include existing request id. Some requests are sent with a fixed id so would be good to rule those out.
Updates #228

fix: update log message to include existing request id

---

roborock/api.py
roborock/version_1_apis/roborock_client_v1.py

Update code to always use  time.monotonic since this is now always available in the required library python version. The motivation is to reduce the number of calls to methods in base classes to reduce the class hierarchy. 
Issue #228

chore: always use time.monotonic

---

roborock/version_1_apis/roborock_client_v1.py
roborock/version_1_apis/roborock_local_client_v1.py
roborock/version_1_apis/roborock_mqtt_client_v1.py

Add additional log messages to track down request id assignments and possible mismatches by logging right after request ids are generated.  Getting a request for a message in the queue is probably a "shouldn't happen" case so also add a log message there.

fix: add additional log messages to track down concurrency errors

---

roborock/containers.py
roborock/version_1_apis/roborock_client_v1.py
roborock/web_api.py

This streamlines my process a bit for getting source code and products. 
As well as improves a few errors.

feat: add product v4 and downloading code

---

README.md

Adds an example on how to use the package without HA

chore: add example

---

tests/test_api.py

Update tests to use asyncio mode in pytest options to avoid needing to tag every test as async. I ran into problems when adding more asyncio tests for the mqtt broker that were resolved by changing this.  Also makes one test async where the constructor depends on the current asyncio loop and logs a warning.

chore: use asyncio mode in tests

---

tests/conftest.py
tests/mock_data.py
tests/mqtt_packet.py
tests/test_api.py
tests/test_containers.py

Add end to end tests of the MQTT client using a fake socket. The tests patch the python socket library used by MQTT and return a fake socket that intercepts the send/recv methods, to avoid using real sockets during the test.
This copies some of the paho mqtt test fixtures and replies with real encoded mqtt packets. Really, this is probably too low level of a test to do in this client library, given we should just mock out the MQTT client. However, that is difficult to do because the client subclasses the MQTT client. Having the end to end tests means we can refactor the class inheritance structure with higher confidence that things won't break.
This adds tests for the async interfaces for connect and disconnect, and also tests with one sample message.

test: add end-to-end tests for the MQTT client

---

roborock/cloud_api.py

Allow type checking in roborock/cloud_api.py, removing the typing guard. Typing seems to pass so this seems safe to do, but will see on CI:
```bash
$ mypy roborock/cloud_api.py           
Success: no issues found in 1 source file
```

chore: allow type checking in roborock/cloud_api.py

---

roborock/api.py
roborock/cloud_api.py
roborock/roborock_future.py
roborock/version_1_apis/roborock_client_v1.py
roborock/version_1_apis/roborock_local_client_v1.py
roborock/version_1_apis/roborock_mqtt_client_v1.py
roborock/version_a01_apis/roborock_client_a01.py
roborock/version_a01_apis/roborock_mqtt_client_a01.py
tests/test_api.py
tests/test_queue.py

Simplify future usage within the api clients by separating how message results and exceptions are passed, using built in exception handling in futures. This raises exceptions instead of returning exceptions. This is a step of simplification on the path to fixing some concurrency issues in the client libraries.
Issue #228

refactor: simplify future usage within the api clients

---

roborock/api.py
roborock/cloud_api.py
roborock/local_api.py
roborock/version_1_apis/roborock_client_v1.py
roborock/version_1_apis/roborock_local_client_v1.py
roborock/version_1_apis/roborock_mqtt_client_v1.py
roborock/version_a01_apis/roborock_client_a01.py
roborock/version_a01_apis/roborock_mqtt_client_a01.py

Update the base classes to use the `abc` package, which provides the infrastructure for defining abstract base classes. Remove variables that are overridden in multiple places so that variables are only set once in the class hierarchy. The fixes include:
- Use `@abstractmethod` to avoid needing the `raise NotImplemented` reducing untested lines of code
- Set `_endpoint` only once, rather than multiple times. Removed the places where it is not used. (Question: Local commands use it when secured with "abc" but does it do anything?)
- Set `_logger` once for each client in the client itself so that the log messages are associated with the actual client being used. This will let us tell the difference between a local client disconnecting and a cloud client disconnecting which is difficult to …

chore: client library inheritance fixes and simplifications

---

tests/conftest.py
tests/mock_data.py
tests/test_local_api_v1.py

Add local API coverage using a fake local transport. This reuses the request/response queue from the MQTT test and mocks out the transport similar to the sockets.
Issue #228

chore: add local api test coverage

---

roborock/cloud_api.py

Pull the overrides related to the MQTT client library into a separate class, to avoid a level of inheritance. This makes it more clear which methods are part of the interaction with the MQTT client vs which are part of other base classes. It also makes it clear which overrides are MQTT client library specific vs part of the other parent classes.
Issue #228

chore: remove level of inheritance in mqtt client

---

.github/workflows/ci.yml
commitlint.config.js
commitlint.config.mjs

This should allow caps and get us past the commitlint breaking change.
Doing this as a fix to alos check and see if semantic release is working on this new repo

fix: bump commitlint and allow caps

---

.github/workflows/ci.yml

This will run the library on python 3.11, 3.12, 3.13 but drop windows and mac platforms. The motivation is that incompatibility issues seem more likely to happen from new python versions rather than different platforms. This matches most other project norms i've seen.

chore: update CI to run on one platform, but multiple python versions

---

roborock/local_api.py
tests/conftest.py
tests/test_local_api_v1.py

Add a test for the room mapping call, then fix the harness to call the right response method for the protocol wrapper object.

fix: Update local API protocol broken during refactoring and add additional tests for API calls

---

roborock/cloud_api.py

Remove methods that were removed in paho-mqtt v2. This means we no longer change the client id when disconnecting. The client id can be used to resume connections, and it seems worth trying to resolve the root cause of a bug in the future explicitly. e.g. we can create a new client library if we want to reset the entire connection.
This should allow https://github.com/Python-roborock/python-roborock/pull/288 to succeed

fix: remove methods no longer available in paho-mqtt

---

poetry.lock
pyproject.toml
roborock/roborock_message.py
tests/test_roborock_message.py

Fix the message constructors to use a factory rather than a fixed constant. The bug is that the function is called only once, rather than on every construction. Add a test to verify that the messages are initialized with unique values.
Issue #228
Issue #222

fix: set unique sequence numbers on outgoing messages

---

poetry.lock
pyproject.toml
roborock/cloud_api.py
roborock/roborock_future.py
roborock/version_a01_apis/roborock_client_a01.py
tests/conftest.py
tests/test_a01_api.py
tests/test_api.py

Explicitly stop the mqtt loop when the client library shuts down to avoid leaking threads. Explicitly release clients during test cleanup, but make it best effort.

chore: fix flaky tests by cleaning up threads

---

roborock/api.py

Update the keepalive logic to log an error message so that we can diagnose disconnects as coming from the device vs being originated by the keepalive logic.

fix: log an explicit message when intentionally resetting the connection

---

roborock/api.py
roborock/cloud_api.py
roborock/local_api.py
roborock/version_1_apis/roborock_local_client_v1.py
roborock/version_1_apis/roborock_mqtt_client_v1.py
roborock/version_a01_apis/roborock_client_a01.py
roborock/version_a01_apis/roborock_mqtt_client_a01.py
tests/conftest.py
tests/test_a01_api.py
tests/test_api.py

Update the class hierarchy for queue_timeout so that it is only set in the base classes. Right now it is passed up through the constructors, but sometimes uses the default arguments and get overwritten. This is an example of the problems with having multiple inheritance.
Issue #228
Update the tests to set a timeout of 10 up from 4 to see if it helps the tests be more resilient to slowness.

fix: fix queue timeout variable and set default in tests of 10 seconds

---

roborock/api.py
roborock/cloud_api.py
roborock/local_api.py
roborock/version_1_apis/roborock_client_v1.py
tests/test_api.py

Two breaking changes:
- Remove the sync APIs. Callers need to update from the `sync_` version to the fully `async_` version. These APIs currenty log warnings when not called from an async when an event loop is not started.
- These APIs will now log when the client library is not shutdown properly. The caller must call the async release methods when shutting down to free any resources rather than relying on the `__del__` method which is not async. This is logged at debug since i'm not sure how reliable it is to check "is_connected"
Issue #228

refactor: breaking change to remove sync APIs

---

roborock/api.py

This had some problems in home assistants unit test. I think it is reasonable to just require clients to shut down things properly and not have this.
This is needed to update python-roborock in Home Assistant.

fix: remove the __del__ warning for disconnected clients

---

roborock/api.py

Ping will always have the same id and there is a strong likelihood that two could be in the waiting queue at the same time and that should be fine for aping
relates to: https://github.com/home-assistant/core/issues/136908#issuecomment-2624484017
This does not fix the relating problem that when an id changes, the system doesn't know how to wait for it.

fix: ignore ping id during id check

---

roborock/web_api.py
tests/conftest.py
tests/test_web_api.py

Some findings from my recent reverse engineering

feat: add commands to add a new device

---

roborock/cli.py
roborock/containers.py
roborock/web_api.py
tests/conftest.py
tests/mock_data.py
tests/test_web_api.py

Solves #102
Thanks to @muinmomin as posted in https://github.com/humbertogontijo/homeassistant-roborock/issues/169#issuecomment-2576255682 I was able to add scene/routine functionality.  
Once this will get released, we can add it to HA, as requested in https://github.com/humbertogontijo/homeassistant-roborock/issues/169 and https://github.com/humbertogontijo/homeassistant-roborock/issues/419

add scenes/routines support

---

roborock/roborock_message.py
roborock/version_1_apis/roborock_client_v1.py

Kind of just a intermediary step so users don't need to get any kind of logging warnings for something we know of.

fix: add some extra data protocol checking

---

roborock/version_1_apis/roborock_client_v1.py

Not really a huge deal - but this means we don't have to do self.coord.api.send_command(RoborockCommand.LOAD_MULTI_MAP, [map_flag])
It can be a lot easier and cleaner.

feat: add load_multi_map function

---

README.md

The links to the documentation and to the supported devices were not working because they were quoted.

Fix Links to documentation

---

roborock/version_1_apis/roborock_client_v1.py

This whole system likely needs some love and refactoring. But for now, we shouldn't be returning a cached value for get_status.
We should update the cached value, but it doesn't make sense for us to return it, as it is the most important command for us to get.

feat: allow forcing of updating cache variables

---

roborock/web_api.py

Hopefully this will help debugging some errors easier.

feat: add some logging for the web api

---

roborock/code_mappings.py

My Roborock Saros 10 is showing a warning log in Home Assistant:
```
Logger: roborock.code_mappings
Source: runner.py:154
First occurred: 17:29:15 (1 occurrences)
Last logged: 17:29:15
Missing RoborockDockTypeCode code: 18 - defaulting to 'unknown'
```
Implemented a similar fix to https://github.com/Python-roborock/python-roborock/pull/343 - Adding the code to `RoborockDockTypeCode`.

Add dock type code 18 for Saros 10

---

roborock/cloud_api.py
roborock/local_api.py
roborock/protocol.py
roborock/version_1_apis/roborock_local_client_v1.py
roborock/version_1_apis/roborock_mqtt_client_v1.py
roborock/version_a01_apis/roborock_mqtt_client_a01.py

This is in preparation for sharin with new device/mqtt code.

chore: Minor refactoring creating functions for transforming bytes

---

roborock/containers.py
roborock/devices/README.md
roborock/devices/__init__.py
roborock/devices/device.py
roborock/devices/device_manager.py
roborock/mqtt/__init__.py
tests/devices/__init__.py
tests/devices/test_device_manager.py
tests/mock_data.py
tests/test_containers.py

Add a device manager that will query home data then create a Device object for each discovered device. The API exposes the home API such that it can be wrapped by the caller with a caching layer.
The device object is a placeholder and will likely be changed in the future to support capabilities.

feat: Add a DeviceManager to perform discovery

---

roborock/cli.py
roborock/cloud_api.py
roborock/containers.py
roborock/mqtt/roborock_session.py
roborock/protocol.py

Add a command line that can connect to the MQTT session and subscribe for messages. Right now it just prints a prefix of the bytes stream.
```shell
% roborock session
Discovered devices: Roborock Downstairs, Roborock Upstairs
INFO:roborock.mqtt.roborock_session:Starting MQTT session
Starting MQTT session...
MQTT session started. Listening for messages...
Stopping MQTT session...
```

feat: Add a CLI for exercising the asyncio MQTT session

---

roborock/cli.py
roborock/devices/device.py
roborock/devices/device_manager.py
roborock/devices/mqtt_channel.py
tests/devices/test_device.py
tests/devices/test_device_manager.py
tests/devices/test_mqtt_channel.py

Update the device manager and device to establish an Mqtt "channel" which is the device-specific subscription in the mqtt session. The channel will be used for decoding messages and sending/receiving RPCs.
Lots of future work needed here including:
- Handle non-mqtt devices
- Add message decoding 
- Add message encoding and receiving of RPCs
- Local connections

feat: Update device manager and device to establish an MQTT subscription

---

roborock/devices/local_channel.py
tests/devices/test_local_channel.py

Add a local channel, similar to the MQTT channel. This is not yet used by the device or device manager.

feat: Add a local channel, similar to the MQTT channel

---

.github/workflows/ci.yml
pyproject.toml
tests/devices/test_mqtt_channel.py
tests/test_api.py

Remove tests that often timeout on CI. This will result in lower test coverage, but probably not worth it given the flakes.

Update tests to improve CI logging to better diagnose timeout

---

tests/devices/test_device_manager.py

Fix warning in device manager test due to the unsub value being assumed a coroutine.
> tests/devices/test_device_manager.py::test_with_device
> tests/devices/test_device_manager.py::test_get_non_existent_device
>   /Users/allen/Development/python-roborock/roborock/devices/device.py:100: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
>     self._unsub()
>   Enable tracemalloc to get traceback where the object was allocated.
>   See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

chore: Fix warning in tests/devices/test_device_manager.py

---

roborock/protocols/v1_protocol.py
roborock/version_1_apis/roborock_client_v1.py
roborock/version_1_apis/roborock_local_client_v1.py
roborock/version_1_apis/roborock_mqtt_client_v1.py
tests/test_api.py
tests/test_local_api_v1.py

Extract the v1 request encoding into a separate module that will be shared with the new device library.

chore: Create module for v1 request encoding

---

roborock/protocols/a01_protocol.py
roborock/version_a01_apis/roborock_client_a01.py
roborock/version_a01_apis/roborock_mqtt_client_a01.py
tests/protocols/__init__.py
tests/protocols/test_a01_protocol.py
tests/test_a01_api.py

Update the a01 encoding and decoding to live in a separate module that can be shared with the new device code. Increase test coverage of the encoding and decoding.
This removes the caching since it was not implemented, and it can be re-added in the new device library.

chore: Move a01 encoding and decoding to a separate module

---

poetry.lock
roborock/cli.py
roborock/devices/device.py
roborock/devices/device_manager.py
roborock/devices/local_channel.py
roborock/devices/v1_channel.py
roborock/protocols/v1_protocol.py
tests/devices/test_device.py
tests/devices/test_device_manager.py
tests/devices/test_local_channel.py
tests/devices/test_v1_channel.py
tests/mock_data.py
tests/protocols/__init__.py
tests/protocols/test_v1_protocol.py

Add a V1Channel class that wraps the MQTT and Local channels and handles getting the network info from mqtt and decidign which channel is available. The local connection does not handle retries yet, which will be fixed in a follow up change.
Most of the PR is for tests exercising corner cases. This PR was heavily coded by Co-pilot.

feat: Add a v1 protocol channel that can send messages across MQTT or Local connections, preferring local

---

roborock/containers.py
tests/test_containers.py

Streamline the container parsing using modern python constructs for iterating over types. This adds support for nested dictionaries, and consolidates a few versions of similar logic into fewer places.

chore: update container parsing using native typing and dataclass

---

roborock/device_features.py

Got these while trying to nail down a better way to fix all the errors with incorrect names for modes or smart mode errors.
This theoretically should make it so we can more dynamically create mop/fan modes. TBD though.
Open to better naming if you can think of it.

feat: add a new type for supported features

---

roborock/containers.py
tests/test_containers.py

Add a helper that extracts the current map from the map status to avoid needing to do this math in the caller.

feat: Add property for accessing the current map from the status object

---

roborock/mqtt/roborock_session.py

Set an explicit marker to check before sleeping/backoff in the mqtt background task loop. This speeds up the mqtt session shutdown test by avoiding an extra sleep before noticing the loop was cancelled. The mqtt tests when from ~11 seconds to ~1 second.

chore: speed up mqtt session shutdown by avoiding a sleep

---

roborock/protocols/v1_protocol.py
roborock/roborock_message.py
roborock/version_1_apis/roborock_local_client_v1.py
tests/protocols/test_v1_protocol.py
tests/test_local_api_v1.py
tests/test_roborock_message.py

Remove the logic for attempting to retry a request which does not work because it is missing an `await` when sending the command, which returns an unwaited coroutine. Since it's already broken we'll just fail with a `RoborockException` and retry at a higher level to keep this simple.

fix: Fix "retry" error handling

---

roborock/broadcast_protocol.py
roborock/containers.py
roborock/protocol.py
tests/test_broadcast_protocol.py

Add L01 to the discovery process

feat: add l01 discovery

---

roborock/protocols/v1_protocol.py
roborock/version_1_apis/roborock_client_v1.py
tests/protocols/test_v1_protocol.py

Map requests will go to our topic, we fail to decode it, and we raise an exception. i worry users will get confused if their log is full of errors when they open their app, so I replaced it with a debug statement instead.

fix: bug where the map requested from the app confuses our system

---

roborock/containers.py
tests/__snapshots__/test_containers.ambr
tests/test_containers.py

This fixes a bug in likely added in #426 when rewriting the object parsing code. This removes the `ignore_keys` attribute and fixes the map flag so that it can be parsed correctly.
Fixes #472
This was previously fixed in https://github.com/Python-roborock/python-roborock/commit/cfaeb419e188510ade5bc1506214c9b3d2afeb18 -- this time, also including a test to ensure we don't have future regressions.

fix: Fix bug parsing MultiMapsListMapInfo

---

roborock/web_api.py
tests/conftest.py
tests/test_web_api.py

Roborock is keeping me on my toes...
All new accounts have to login via the v4 endpoint (existing accounts can login with it as well) as accounts are now per country. i.e. you can make a new account in Cambodia with the exact same email.
Fixes #485
We will need to figure out how to get the user to specify their country code and country abbreviation, open to any ideas via a follow up or in HA itself.

feat: add v4 for code login

---

.github/workflows/pages.yml

Try to fix CI for building pdoc. Example failure https://github.com/Python-roborock/python-roborock/actions/runs/18082881173

chore: Try `poetry run pdoc` to fix CI

---

roborock/version_1_apis/roborock_client_v1.py

Using `return` in a finally clauses is a SyntaxWarning in Python 3.14.

fix: return in finally

---

roborock/cli.py
roborock/devices/traits/v1/__init__.py
roborock/devices/traits/v1/consumeable.py
tests/devices/traits/v1/test_consumable.py
tests/protocols/__snapshots__/test_v1_protocol.ambr
tests/protocols/testdata/v1_protocol/get_consumeables.json

Add a trait that reads and writes consumables. Add tests for the protocol parsing snapshot tests and some of the trait tests. Add the commands to the CLI.

feat: add support for getting and reseting consumables

---

tests/conftest.py
tests/devices/test_v1_channel.py

```py
tests/devices/test_v1_channel.py::test_v1_channel_command_encoding_validation
/.../python-roborock/roborock/devices/v1_channel.py:233:
RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
self._local_channel.close()
```
Close is a normal function, not async.
https://github.com/Python-roborock/python-roborock/blob/e9ba1e3be3ae9119266225190227c0de6dec16e6/roborock/devices/local_channel.py#L73-L80

chore: fix test warning

---

roborock/cli.py
roborock/devices/device_manager.py
roborock/devices/traits/v1/__init__.py
roborock/devices/traits/v1/common.py
roborock/devices/traits/v1/map_content.py
roborock/devices/v1_channel.py
roborock/devices/v1_rpc_channel.py
roborock/map/__init__.py
roborock/protocols/v1_protocol.py
tests/devices/test_v1_channel.py
tests/devices/test_v1_device.py
tests/devices/traits/v1/fixtures.py
tests/devices/traits/v1/test_map_content.py
tests/protocols/test_v1_protocol.py

Add a v1 device trait for map contents
This uses the map parser library to return an image and the parsed data from from get v1 maps API. Internally, a new RPC channel is added that is configured to properly encode and parse map responses. Two new CLI options are added for exercising the image content and map metadata functionality.

Add a v1 device trait for map contents
