Python-roborock/python-roborock

roborock/api.py
roborock/code_mappings.py
roborock/containers.py
roborock/typing.py
tests/test_containers.py

I don't have a dock so I would wait to set the version for the custom component until I have someone test this. I just wanted to get this added here so I can give them a demo version of the custom component to try.
- added new commands
- Added dock summary, which changes based on which dock you have
- changed to local imports rather than full package imports

Add Docking Information

---

roborock/typing.py

Added some new commands I found while using wireshark

chore: add new commands

---

roborock/api.py

I didn't realize you figured out the networking function (if you feel like it, i'd be curious to know how)
Added a function to get networking information. 
At least in the core version, I'm going to make it so that devices will store their mac + ip.

feat: add networking function

---

pyproject.toml

Per recommendation here: 
https://github.com/python-semantic-release/python-semantic-release/issues/575#issuecomment-1500904789

fix: semantic release not updating changelong

---

roborock/code_mappings.py

Per issue https://github.com/humbertogontijo/homeassistant-roborock/issues/253#issuecomment-1519191762

fix: added missing docks

---

roborock/const.py

This fixes #52 , verified the model string with my own S8 Pro Ultra.

fix: changed incorrect s8 pro ultra string

---

roborock/containers.py

did this as a fix because I didn't want it to be a major release tag.

fix: add types for S8

---

.gitignore
docs/Makefile
docs/make.bat
docs/source/api.rst
docs/source/conf.py
docs/source/index.rst
docs/source/usage.rst

basic skeleton for docs so I can start adding and testing with readthedocs

feat: add docs

---

roborock/code_mappings.py

fix: change e2 fan codes

---

roborock/containers.py
tests/test_containers.py

Core doesn't like calculations being done in core, so I moved the division to the api.

feat: moving clean area to api

---

roborock/code_mappings.py

Adds dock error code 34 that indicates a duct blockage on my S7 Maxv Ultra

feat: adds code for duct blockage 

---

roborock/api.py
roborock/containers.py
roborock/exceptions.py

Adds Unknown Method error
Time for the dnd and valley.
I need to create a setter for those, but I need to do some reverse engineering as I can't get the set command to actually change the timer.

feat: add time datetime for valley

---

roborock/cli.py

cli was passing params as a string

fix: cli json serializing

---

roborock/api.py
roborock/cloud_api.py
roborock/containers.py
roborock/local_api.py
roborock/roborock_typing.py

Adding diagnostic data that will allow users to get diagnostic data rather than having to use debug. Also adds stuff for flow led

feat: add diagnostic data and extra containers

---

pyproject.toml
roborock/api.py
roborock/cloud_api.py
roborock/command_cache.py
roborock/local_api.py
roborock/roborock_typing.py
roborock/util.py

This is my proposal for command cache. Fetch a single time and evict if set or change is called(Only for the methods in CacheableAttribute enum)

feat: adding command cache

---

pyproject.toml

a few things I saw suggested to try to fix our poetry issues

chore: update pyproject

---

.github/workflows/ci.yml

Reverts humbertogontijo/python-roborock#89

fix: revert semantic release

---

roborock/api.py
roborock/cloud_api.py
roborock/local_api.py
roborock/util.py

Makes logs like this so that we can more easily identify what logsare coming from what vacuum when there are multiple devices on an account.

feat: add device name to logs

---

roborock/api.py

Per findings here: https://github.com/home-assistant/core/issues/101040?notification_referrer_id=NT_kwDOATUcd7M3ODc0MjYxOTUyOjIwMjU3OTEx

fix: parsing potential list of clean record

---

pyproject.toml

https://github.com/humbertogontijo/python-roborock/commit/aae48b1395698136ca90b7fe7386a1b6ea8aaa9c
I think this was added by mistake? Unless I'm missing something

fix:remove alexapy

---

roborock/code_mappings.py

https://github.com/home-assistant/core/issues/100784#issuecomment-1739436005
Per conversations here - it looks like 207 is needed as well

fix: add missing 207 code

---

docs/source/api_commands.rst

Update api_commands.rst app_goto_target

---

roborock/containers.py

Removes a chunk of problematic code until I can fix it.

fix: remove problematic code

---

roborock/api.py

I am trying to debug an issue with some users map, but their data is useless to me without the nonce

feat: add nonce to diagnostic data

---

pyproject.toml

Another breaking change from the version bump

fix: semantic release versioning tag

---

.github/workflows/ci.yml

solution found here: https://github.com/semantic-release/semantic-release/issues/2496
Hopefully we can get through this soon - This was such a large refactor in the semantic release package. So many breaking changes and poorly documented

fix: give ci more permissions

---

.github/workflows/ci.yml

Found this suggested here:
https://github.com/orgs/community/discussions/26694

fix: add gh_token to checkout

---

.github/workflows/ci.yml

Will try once without this as well.

fix: add config github actions

---

tests/test_api.py

Add tests to improve the `api` and `cloud_api` module test coverage around future and error handling.

test: improve api and cloud_api test coverage

---

roborock/local_api.py

Remove one level of local client inheritence by pulling out `asyncio.Protocol` into a separate class. This is a fairly small change, but makes it clear which methods are public parts of the class that callers can invoke vs which can are internal callbacks used by the transport.

chore: remove one level of local client inheritence

---

roborock/cli.py

release the api instead of deleting it now that del no longer exists.

fix: delete in cli

---

roborock/code_mappings.py

Got these from here: https://github.com/home-assistant/core/issues/133846#issuecomment-2652301477

fix: q revo curv mappings

---

roborock/code_mappings.py
roborock/exceptions.py
roborock/version_1_apis/roborock_client_v1.py
roborock/web_api.py

Closes #339
Relates to: https://github.com/home-assistant/core/issues/139592?notification_referrer_id=NT_kwDOATUcd7QxNTA2OTA1ODUzMToyMDI1NzkxMQ#issuecomment-2695114049

fix: add error for web calls and saros dock

---

roborock/roborock_typing.py

Silly mistake.
if attribute 
instead of
if attribute is not None

fix: bad dock summary logic

---

roborock/web_api.py
tests/test_api.py

This allows passing in a clientsession object. If one isn't provided, it will auto create one.

feat: allow passing in clientsession

---

roborock/code_mappings.py

Relates to: https://github.com/home-assistant/core/issues/145603

fix: add missing finish reason

---

.github/workflows/gemini-dispatch.yml
.github/workflows/gemini-invoke.yml
.github/workflows/gemini-review.yml
.github/workflows/gemini-scheduled-triage.yml
.github/workflows/gemini-triage.yml
.gitignore

These are the default ones they recommend setting up. I disabled scheduled triage as I am just using my free api key, so I don't want it to burn through limits
Followed guide here: https://github.com/google-github-actions/run-gemini-cli#quick-start

chore: add gemini default ci actions

---

roborock/cli.py
roborock/devices/device_manager.py
roborock/devices/traits/v1/__init__.py
roborock/devices/traits/v1/common.py
roborock/devices/traits/v1/maps.py
tests/devices/test_v1_device.py
tests/devices/traits/v1/fixtures.py
tests/devices/traits/v1/test_maps.py
tests/protocols/__snapshots__/test_v1_protocol.ambr
tests/protocols/testdata/v1_protocol/get_multi_maps_list.json

Add v1 api support for the list of maps. In a follow up PR, will add additional things like room information.

feat: add v1 api support for the list of maps

---

roborock/cli.py

I've previously just locally done this change and never pushed it. Otherwise you get a not implemented error.

fix: cli on windows
